In [33]:
import music21
from music21 import chord, note, converter
file = r"C:\Users\ppawa\Pranav\Study\Coding\Generative Deep Learning\Projects\Music-Generator\Berlin_Air_March__Lincke__RW.mid"
original_score = converter.parse(file).chordify()
original_score.show('text')


{0.0} <music21.metadata.Metadata object at 0x197c7a2bad0>
{0.0} <music21.stream.Measure 1 offset=0.0>
    {0.0} <music21.instrument.Instrument 'Berlin Air March (Lincke) Kupfernagel RW 1905: '>
    {0.0} <music21.clef.TrebleClef>
    {0.0} <music21.tempo.MetronomeMark Quarter=100>
    {0.0} <music21.key.Key of C major>
    {0.0} <music21.meter.TimeSignature 4/4>
    {0.0} <music21.note.Rest 3.5ql>
    {3.5} <music21.chord.Chord G2 B-2 G3 B-3 G4 G5>
    {3.75} <music21.chord.Chord B-4 B-5>
{4.0} <music21.stream.Measure 2 offset=4.0>
    {0.0} <music21.chord.Chord B-4 B-5>
    {0.0833} <music21.note.Rest 16th>
    {0.3333} <music21.chord.Chord G2 G3 G4 G5>
    {0.6667} <music21.note.Rest 1/3ql>
    {1.0} <music21.chord.Chord F2 F3 F4 F5>
    {1.25} <music21.note.Rest 16th>
    {1.5} <music21.chord.Chord E-2 E-3 E-4 E-5>
    {1.75} <music21.chord.Chord G2 G3 G4 G5>
    {2.0833} <music21.note.Rest 16th>
    {2.3333} <music21.chord.Chord E-2 E-3 E-4 E-5>
    {2.6667} <music21.note.Rest 1/12

In [34]:
notes = []
durations = []

for element in original_score.flat:

    if isinstance(element, chord.Chord):
        notes.append('.'.join(n.nameWithOctave for n in element.pitches))
        durations.append(element.duration.quarterLength)

    if isinstance(element, note.Note):
        if element.isRest:
            notes.append(str(element.name))
            durations.append(element.duration.quarterLength)
        else:
            notes.append(str(element.nameWithOctave))
            durations.append(element.duration.quarterLength)

C:\Users\ppawa\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3577: Music21DeprecationWarning: .flat is deprecated.  Call .flatten() instead
  exec(code_obj, self.user_global_ns, self.user_ns)


In [35]:
print(notes)
print(durations)

['G2.B-2.G3.B-3.G4.G5', 'B-4.B-5', 'B-4.B-5', 'G2.G3.G4.G5', 'F2.F3.F4.F5', 'E-2.E-3.E-4.E-5', 'G2.G3.G4.G5', 'E-2.E-3.E-4.E-5', 'B-1.B-2.B-3.B-4', 'B-1.C2.B-2.C3.C4.C5', 'B-1.C2.B-2.C3.B-3.C4.B-4.C5', 'B-1.B-3.B-4', 'E-2.E-3.B-3.G4.B-4', 'F2.F3.B-3.F4.B-4', 'G2.G3.B-3.E-4.B-4', 'B-1.B-2.B-3.D4.F4.B-4', 'B-3.D4.F4.G#4.B-4.D5.F5.G#5.B-5', 'B-5', 'E-2.B-2.E-3.B-4.G5.B-5', 'G3.B-3.E-4.B-4.G5', 'B-1.B-2.B-4.F5', 'F5', 'G3.B-3.E-4.B-4.E-5', 'E-2.E-3.B-4.G5', 'G3.B-3.E-4.B-4.E-5', 'B-1.B-2.G3.B-4', 'B-3.E-4', 'E-2.E-3.B-4.G5.B-5', 'G3.B-3.E-4', 'B-1.B-2.C5.G5.C6', 'G3.B-3.E-4.G5', 'F2.F3.D5.G#5.D6', 'G#3.B-3.D4.D5.G#5.D6', 'B-1.B-2', 'G#3.B-3.D4', 'D2.D3.C5.G#5.C6', 'G#3.B-3.D4.B-4.G#5', 'B-1.B-2.B-4.G5', 'G#3.B-3.D4.B-4.F5', 'D2.D3.B-4.G#5', 'G#3.B-3.D4.B-4.F5', 'B-1.B-2.B-4', 'G#3.B-3.D4', 'F2.F3.C5.G#5.C6', 'G#3.B-3.D4', 'B-1.B-2.G#3.B-3.D4.D5.G#5.D6', 'B-1.B-2.D5.G#5.D6', 'G#3.B-3.D4.G#5', 'E-2.E-3.C5.G5.C6', 'G3.B-3.E-4.C5.G5.C6', 'B-1.B-2', 'G3.B-3.E-4', 'E-2.E-3.B-4.G5.B-5', 'G3.B-3.E

In [43]:
unique_notes = sorted(set(notes))
unique_durations = sorted(set(durations))
note_to_int = {note: idx for idx, note in enumerate(unique_notes)}
duration_to_int = {duration: idx for idx, duration in enumerate(unique_durations)}

In [44]:
print(note_to_int)
print(duration_to_int)

{'B-1': 0, 'B-1.B-2': 1, 'B-1.B-2.B-3.B-4': 2, 'B-1.B-2.B-3.D4.F4.B-4': 3, 'B-1.B-2.B-4': 4, 'B-1.B-2.B-4.B-5': 5, 'B-1.B-2.B-4.F5': 6, 'B-1.B-2.B-4.G5': 7, 'B-1.B-2.C5.D5.G#5.C6': 8, 'B-1.B-2.C5.G#5.C6': 9, 'B-1.B-2.C5.G5.C6': 10, 'B-1.B-2.D4.G#4.B-4': 11, 'B-1.B-2.D5.E-5': 12, 'B-1.B-2.D5.E-5.F5': 13, 'B-1.B-2.D5.F5.G#5.D6': 14, 'B-1.B-2.D5.G#5.D6': 15, 'B-1.B-2.E-5': 16, 'B-1.B-2.E-5.G5': 17, 'B-1.B-2.E4.G4.B-4.D5.E5.G5': 18, 'B-1.B-2.E5.F5': 19, 'B-1.B-2.F5.B-5.C#6.F6': 20, 'B-1.B-2.G#3.B-3.D4.D5.G#5.D6': 21, 'B-1.B-2.G3.B-4': 22, 'B-1.B-2.G4.B-4.E-5.G5': 23, 'B-1.B-3.B-4': 24, 'B-1.C#2.F2.B-2.F5.B-5.C#6.F6': 25, 'B-1.C2.B-2.C3.B-3.C4.B-4.C5': 26, 'B-1.C2.B-2.C3.C4.C5': 27, 'B-1.E4.E5': 28, 'B-2.B-3.C#5': 29, 'B-2.B-3.C#5.D5': 30, 'B-2.B-3.C5': 31, 'B-2.B-3.C5.C#5.F5': 32, 'B-2.B-3.C5.G5.C6': 33, 'B-2.B-3.D5.D6': 34, 'B-2.B-3.E-4.G4.B-4': 35, 'B-2.B-3.E-4.G4.C5': 36, 'B-2.B-3.F4.B-4.F5': 37, 'B-2.B-3.G#4.C5.C#5.F5': 38, 'B-2.B-3.G4.B-4.D5.G5': 39, 'B-2.B-3.G4.B-4.G5': 40, 'B-2.B-3.

In [46]:
import numpy as np
from keras.utils import to_categorical

note_ints = [note_to_int[note] for note in notes]
duration_ints = [duration_to_int[duration] for duration in durations]

sequence_length = 32

X_notes = []
y_notes = []
X_durations = []
y_durations = []

for i in range(len(note_ints) - sequence_length):
    X_notes.append(note_ints[i:i + sequence_length])
    y_notes.append(note_ints[i + sequence_length])
    X_durations.append(duration_ints[i:i + sequence_length])
    y_durations.append(duration_ints[i + sequence_length])

X_notes = np.array(X_notes)
y_notes = np.array(y_notes)
X_durations = np.array(X_durations)
y_durations = np.array(y_durations)

y_notes = to_categorical(y_notes, num_classes=len(unique_notes))
y_durations = to_categorical(y_durations, num_classes=len(unique_durations))

print("X_notes shape:", X_notes.shape)
print("y_notes shape:", y_notes.shape)
print("X_durations shape:", X_durations.shape)
print("y_durations shape:", y_durations.shape)

X_notes shape: (673, 32)
y_notes shape: (673, 292)
X_durations shape: (673, 32)
y_durations shape: (673, 8)


In [52]:
print(X_notes)
print(X_durations)
print(y_notes)
print(y_durations)

[[260  66  66 ...  10 287 201]
 [ 66  66 270 ... 287 201 249]
 [ 66 270 203 ... 201 249   1]
 ...
 [154 159 181 ... 128 177 203]
 [159 181 229 ... 177 203 270]
 [181 229 154 ... 203 270 241]]
[[2 2 0 ... 3 3 3]
 [2 0 3 ... 3 3 3]
 [0 3 2 ... 3 3 2]
 ...
 [2 3 3 ... 2 3 3]
 [3 3 3 ... 3 3 2]
 [3 3 2 ... 3 2 2]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
